version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=BitirmeProjesi'
      - 'POSTGRES_PASSWORD=bitirmeProjesi'
      - 'POSTGRES_USER=barishafize'
    ports:
      - '5432:5432'


  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'




