spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BitirmeProjesi
    username: barishafize
    password: bitirmeProjesi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      id:
        new-generator-mappings: true
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect


  docker:
    compose:
      enabled: true

      file: C:\Users\Baris\OneDrive - ktun.edu.tr\Masaustu\SpringBoot\Bitirme Projesi\Bitirme\BitirmeProjesi\docker-compose.yml
      services:
        - postgres
        - redis


datasource:
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    connection-timeout: 20000
    pool-name: HikariPool

server:
  port: 8082