spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BitirmeProjesi
    username: barishafize
    password: bitirmeProjesi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      id:
        new-generator-mappings: true
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 686213888927-jahnrgm8590h9hkobg59efdvqiljkrtv.apps.googleusercontent.com # Google Developer Console'dan aldığınız client ID
            client-secret: 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  # Google Developer Console'dan aldığınız client secret
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/oauth2/code/google
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo

  docker:
    compose:
      enabled: true

      file: C:\Users\Baris\OneDrive - ktun.edu.tr\Masaustu\SpringBoot\Bitirme Projesi\Bitirme\BitirmeProjesi\docker-compose.yml
      services:
        - postgres
        - redis


datasource:
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    connection-timeout: 20000
    pool-name: HikariPool

server:
  port: 8082