spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: baris.butun15@gmail.com
    password: jndg xybh wvow uiny
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true




  datasource:
    url: jdbc:postgresql://localhost:5432/BitirmeProjesi
    username: barishafize
    password: bitrmeProjesi
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      id:
        new-generator-mappings: true
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 686213888927-jahnrgm8590h9hkobg59efdvqiljkrtv.apps.googleusercontent.com # Google Developer Console'dan aldığınız client ID
            client-secret: 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  # Google Developer Console'dan aldığınız client secret
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/oauth2/code/google
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo

  docker:
    compose:
      enabled: true
      file: C:\Users\Baris\OneDrive - ktun.edu.tr\Masaustu\SpringBoot\Bitirme Projesi\Bitirme\BitirmeProjesi\Docker_Elasticsearch_Kibana_Logstash_Postgre\docker-compose.yml
      services:
        - postgres
        - elasticsearch
        - kibana
        - logstash
        - redis






  elasticsearch:
    restclient:
      uris: https://localhost:9200
      ssl:
        enabled: true
        key-store: C:/Users/Baris/OneDrive - ktun.edu.tr/Masaustu/SpringBoot/Bitirme Projesi/Bitirme/BitirmeProjesi/src/main/resources/keystore.p12
        key-store-password: 123456B
        trust-store: C:/Users/Baris/OneDrive - ktun.edu.tr/Masaustu/SpringBoot/Bitirme Projesi/Bitirme/BitirmeProjesi/src/main/resources/truststore.jks
        trust-store-password: 123456B
        key-store-type: PKCS12
        key-alias: es01
    username: elastic
    password: 123456B
  data:
    redis:
      host: localhost
      port: 6379  # Eğer Redis şifreliyse buraya ekleyebilirsin, aksi halde boş bırakabilirsin
      timeout: 60000 # (ms cinsinden) Redis bağlantısı zaman aşımı süresi
      lettuce:
        pool:
          max-active: 10  # Maksimum aktif bağlantı sayısı
          max-idle: 5      # Maksimum boşta bekleyen bağlantı sayısı
          min-idle: 1      # Minimum boşta bekleyen bağlantı sayısı
          max-wait: 5000




server:
  port: 8082

datasource:
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    connection-timeout: 20000
    pool-name: HikariPool

logging:
  level:
    root: INFO
    com.example: DEBUG
  loggers:
    - name: org.springframework.web
      level: ERROR
  file:
    path: C:\Users\Baris\OneDrive - ktun.edu.tr\Masaustu\SpringBoot\Bitirme Projesi\Bitirme\BitirmeProjesi\logs

admin:
  email: f211220005@ktun.edu.tr
  password: 1234

